---
# tasks file for ansible_role_scibuilder



- name: Create the local folder for scibuilder
  ansible.builtin.file:
    path: "{{ scibuilder_local_folder}}"
    state: directory


- name: Install git
  ansible.builtin.dnf:
    name: git
    state: present


- name: Check out scibuilder
  ansible.builtin.git:
    dest: "{{ scibuilder_local_folder}}/scibuilder"
    repo: "https://github.com/scifihpc/scibuilder.git"

- name: Ensure a unix-group for scibuilder exists
  ansible.builtin.group:
    name: "{{ scibuilder_user_name }}"
    gid:  "{{ scibuilder_user_gid  }}"
    state: present
    
    
- name: Create user account for scibuilder
  ansible.builtin.user:
    name:  "{{ scibuilder_user_name }}"
    uid:   "{{ scibuilder_user_uid  }}"
    group: "{{ scibuilder_user_name }}"
  
