---
# tasks file for ansible_role_scibuilder




- name: Install git
  ansible.builtin.dnf:
    name: git
    state: present


- name: Check out scibuilder
  ansible.builtin.git:
    dest: "{{ scibuilder_local_folder}}/scibuilder"
    repo: "https://github.com/scifihpc/scibuilder.git"
  become: yes
  become_user: "{{scibuilder_user_name}}"

- name: Ensure a unix-group for scibuilder exists
  ansible.builtin.group:
    name: "{{ scibuilder_user_name }}"
    gid:  "{{ scibuilder_user_gid  }}"
    state: present


- name: Create user account for scibuilder
  ansible.builtin.user:
    name:  "{{ scibuilder_user_name }}"
    uid:   "{{ scibuilder_user_uid  }}"
    group: "{{ scibuilder_user_name }}"

- name: Create the local folder for scibuilder
  ansible.builtin.file:
    path: "{{ scibuilder_local_folder}}"
    state: directory
    owner: "{{ scibuilder_user_name }}"
    group: "{{ scibuilder_user_name }}"



- name: install podman
  ansible.builtin.dnf:
    name: ["podman", "podman-docker","container-selinux"]
    state: present

# https://github.com/containers/podman/issues/3234
#- name: uninstall  container-selinux
#  ansible.builtin.dnf:
#    name: ["container-selinux"]
#    state: absent
#- name: reinstall  container-selinux
#  ansible.builtin.dnf:
#    name: ["container-selinux"]
#    state: present




- name: create folder for runner
  ansible.builtin.file:
    path: "{{ scibuilder_local_folder}}/runner_{{ item }}"
    state: directory
    group: "{{scibuilder_user_name}}"
    owner: "{{scibuilder_user_name}}"
  loop: "{{ github_runner_name }}"


# https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners
- name: Download & Unarchive runner package
  ansible.builtin.unarchive:
    src:  "{{ github_runner_url }}{{github_runner_filename}}"
    dest: "{{ scibuilder_local_folder}}/runner_{{ item }}"
    remote_src: yes
    group: "{{scibuilder_user_name}}"
    owner: "{{scibuilder_user_name}}"
  loop: "{{ github_runner_name }}"

- name: install sudo to work as a different user
  ansible.builtin.dnf:
    name: ["sudo"]
    state: present

- name: install runner dependencies
  ansible.builtin.dnf:
    name: ["libicu"]
    state: present


- name: Configure the runner
  ansible.builtin.command:
    cmd: "./config.sh --url https://github.com/{{github_runner_org}}/{{ github_runner_repo }} --token {{ github_runner_token }} --unattended --name {{ item }} --replace"
    chdir:  "{{ scibuilder_local_folder}}/runner_{{ item }}"
    creates: "{{ scibuilder_local_folder}}/runner_{{ item }}/svc.sh"
  become: yes
  become_user: "{{scibuilder_user_name}}"
  loop: "{{ github_runner_name }}"

# https://docs.github.com/en/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service
- name: Install runner as a service
  ansible.builtin.command:
    cmd: "./svc.sh install {{ scibuilder_user_name }}"
# The version without a username would create a runner running as root
#    cmd: "./svc.sh install"
    chdir:  "{{ scibuilder_local_folder}}/runner_{{ item }}"
    creates: "/etc/systemd/system/actions.runner.{{github_runner_org}}-{{github_runner_repo}}.{{ item }}.service"
  loop: "{{ github_runner_name }}"

- name: Start the service
  ansible.builtin.systemd:
    state: started
    name: "actions.runner.{{github_runner_org}}-{{github_runner_repo}}.{{ item }}.service"
  tags: ["start_runner"]
  loop: "{{ github_runner_name }}"



# loginctl enable-linger      2000407
# usermod --add-subuids 100000-165535 --add-subgids 100000-165535 triton-ci
# usermod --add-subuids 400100000-400165535 --add-subgids 400100000-400165535 triton-ci
# systemctl start podman.socket
# touch /etc/containers/nodocker

# https://access.redhat.com/solutions/6986578
#  setenforce 0
#  dnf install libsemanage
#  dnf reinstall container-selinux
#  setenforce 1 
#
